- name: make sure group mosquitto exists
  become: true
  ansible.builtin.group:
    name: mosquitto
    state: present
    gid: 1883

- name: make sure host mosquitto user exists and add to group ssl-cert
  become: true
  ansible.builtin.user:
    name: mosquitto
    uid: 1883
    group: mosquitto
    groups: ssl-cert
    append: yes
  register: mos_user
  

- name: Get user uid as fact to use in template
  set_fact:
      mosquitto_uid: "{{ mos_user.uid }}"
      mosquitto_gid: "{{ mos_user.group }}"

- name: Ensure the ssl-cert group exists and get details
  ansible.builtin.group:
    name: ssl-cert
    state: present
  register: ssl_cert_group

- name: Get ssl-cert gid as fact to use in template
  set_fact:
      ssl_cert_gid: "{{ ssl_cert_group.gid }}"

- name: Copy the compose file
  become: true
  template:
    src: templates/compose.yaml
    dest: "{{ docker_compose_dir }}/compose.mosquitto.yaml"
  register: compose_file

- name: Create the mosquitto_mqtt persistent config directory
  become: true
  ansible.builtin.file:
    path: "{{ docker_dir }}/mosquitto/config"
    state: directory
    owner: '{{ mosquitto_uid }}'
    group: '{{ mosquitto_gid }}'
    mode: '0755'

- name: Create the mosquitto_mqtt persistent data directory
  become: true
  ansible.builtin.file:
    path: "{{ docker_dir }}/mosquitto/data"
    state: directory
    owner: '{{ mosquitto_uid }}'
    group: '{{ mosquitto_gid }}'
    mode: '0755'

- name: Create the mosquitto_mqtt persistent log directory
  become: true
  ansible.builtin.file:
    path: "{{ docker_dir }}/mosquitto/log"
    state: directory
    owner: '{{ mosquitto_uid }}'
    group: '{{ mosquitto_gid }}'
    mode: '0755'

- name: check whether passwd file exists
  stat:
    path: "{{ docker_dir }}/mosquitto/config/passwd"
  register: passwd_file

- name: Create empty passwd file
  become: true
  ansible.builtin.file:
    path: "{{ docker_dir }}/mosquitto/config/passwd"
    state: touch
    owner: '{{ mosquitto_uid }}'
    group: '{{ mosquitto_gid }}'
    mode: '0700'
  when: not passwd_file.stat.exists

- name: Copy the config file
  become: true
  template:
    src: templates/mosquitto.conf
    dest: "{{ docker_dir }}/mosquitto/config/mosquitto.conf"
  notify: start mosquitto

- name: Flush handlers #force preceeding handler to run immediately
  meta: flush_handlers

- name: Set mosquitto passwd in container
  become: true
  community.docker.docker_container_exec:
    container: mosquitto
    chdir: /mosquitto/config
    command: "mosquitto_passwd -c  -b passwd {{mqtt_user}} {{mqtt_password}}"
  when: not passwd_file.stat.exists
  notify: restart mosquitto

- name: Flush handlers #force preceeding handler to run immediately
  meta: flush_handlers


