- name: start mosquitto
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    files:
    - compose.mosquitto.yaml

- name: restart mosquitto
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    files:
    - compose.mosquitto.yaml
    state: restarted
